instaworktakehome/urls.py
from django.contrib import admin
from django.urls import include, path
from usermanagement import views as usermanagement_views

app_name = 'usermanagement'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', usermanagement_views.UserListView.as_view(), name='index'),
    path('edit/<pk>/', usermanagement_views.EditView.as_view(), name='edit'),
    path('edit/submitedit/<int:user_id>/', usermanagement_views.submitedit, name='submitedit'),
    path('delete/<int:user_id>/', usermanagement_views.delete, name='delete'),
    path('createnewuser/', usermanagement_views.create_new_user, name='createnewuser'),
    path('new/', usermanagement_views.new, name='new'),
]

usermanagement/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    role = models.CharField(max_length=8)

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name

class UserForm (ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'number', 'role']

usermanagement/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views.generic import ListView, DetailView
from django.views.decorators.csrf import csrf_exempt
from .models import User, UserForm

class UserListView(ListView):
    model = User
    template_name = 'users/index.html'

class EditView(DetailView):
    model = User
    template_name = 'edit/edit.html'

@csrf_exempt
def submitedit(request, user_id):
    user = User.objects.get(id=user_id)
    form = UserForm(request.POST, instance=user)
    form.save()

    return HttpResponse('ok')

@csrf_exempt
def delete(request, user_id):
    user = User.objects.get(id=user_id)
    user.delete()
    return HttpResponseRedirect('ok')

@csrf_exempt
def create_new_user(request):
    user = UserForm(request.POST)
    user.save()

    return HttpResponseRedirect('ok')

def new(request):
    template = loader.get_template('new/new.html')
    context = {}
    return HttpResponse(template.render(context, request))

usermanagement/templates/edit/edit.html
<html>
    <head>
        <title>Test</title>
    </head>

    <body>
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <div class="wrapper">
            <div class="title">Editing {{ user.first_name }}</div>
            <div class="subtitle">Info</div>
            <form action="{% url 'submitedit' user.id %}" method="POST"></form>
                {% csrf_token %}
                <input class="text_input" type="text" id="first_name" value="{{ user.first_name }}" />
                <input class="text_input" type="text" id="last_name" value="{{ user.last_name }}" />
                <input class="text_input" type="text" id="number" value="{{ user.number }}" />
                <input class="text_input" type="text" id="email" value="{{ user.email }}" /> <br /> <br />

                <div class="subtitle">Role</div>
                {% if user.role == 'admin' %}
                    <input class="radio_input" type="radio" id="admin" name="role" checked/>
                {% else %}
                    <input class="radio_input" type="radio" id="admin" name="role"/>
                {% endif %}
                    <label for="admin">Admin - Can delete users</label>
                    <br />

                {% if user.role == 'user' %}
                    <input class="radio_input" type="radio" id="user" name="role" checked/>
                {% else %}
                    <input class="radio_input" type="radio" id="user" name="role"/>
                {% endif %}
                    <label for="user">Regular - Can't delete users</label>
                    <br />


                <button class="button" onclick="submit()" class="submit_button">Save</button>
                <button class="button" onclick="_delete()" class="delete_button">Delete</button>
            </form>

        </div>
    </body>
    <script>
        // Using submit function instead of form due to issues with submit button. 
        // Was faster to create a handler function instead.
        const submit = () => {
            const first_name = document.getElementById("first_name").value;
            const last_name = document.getElementById("last_name").value;
            const number = document.getElementById("number").value;
            const email = document.getElementById("email").value;
            const role = document.querySelector('input[name="role"]:checked').id;

            const params = new URLSearchParams();
            params.append("first_name", first_name);
            params.append("last_name", last_name);
            params.append("number", number);
            params.append("email", email);
            params.append("role", role);

            fetch("{% url 'submitedit' user.id %}", { method: "POST", body: params })
                .then(window.location.href = "{% url 'index' %}");
        }

        const _delete = () => {
            fetch("{% url 'delete' user.id %}", { method: "GET" }).
                then(window.location.href = "{% url 'index' %}");
        }
    </script>
</html>

usermanagement/templates/new/new.html
<html>
    <head>
        <title>Test</title>
    </head>

    <body>
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <div class="wrapper">
            <div class="title">New User</div>
            <form>
                <input class="text_input" type="text" id="first_name" placeholder="First Name" />
                <input class="text_input" type="text" id="last_name" placeholder="Last Name" />
                <input class="text_input" type="text" id="number" placeholder="Number" />
                <input class="text_input" type="text" id="email" placeholder="Email" /> <br /> <br />
                
                <input class="radio_input" type="radio" id="admin" name="role" />
                <label for="admin">Admin - Can delete users</label>
                <br />

                <input class="radio_input" type="radio" id="user" name="role" checked />
                <label for="user">Regular - Can't delete users</label>
            </form>
            <button class="button" onclick="submit()" class="submit_button">Save</button>
        </div>
    </body>

    <script>
        const submit = () => {
            const first_name = document.getElementById("first_name").value;
            const last_name = document.getElementById("last_name").value;
            const number = document.getElementById("number").value;
            const email = document.getElementById("email").value;
            const role = document.querySelector('input[name="role"]:checked').id;

            const params = new URLSearchParams();
            params.append("first_name", first_name);
            params.append("last_name", last_name);
            params.append("number", number);
            params.append("email", email);
            params.append("role", role);

            fetch("{% url 'createnewuser' %}", {
                method: "POST",
                body: params,
            }).then(window.location.href = "{% url 'index' %}");
        }
    </script>
</html>

usermanagement/templates/users/index.html
<html>
    <head>
        <title>Test</title>
    </head>

    <body>
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles.css' %}">
            <div class="wrapper">
                <div class="title">Users</div>
                <div class="count">There are {{object_list.count}} users!</div>

                <a href="{% url 'new' %}">
                    <center>
                        <div class="button">New User</div>
                    </center>
                </a>
            {% for user in user_list %}
            <a href="/edit/{{ user.id }}/">
                <div class="user">
                    <div class="name">
                        {{ user.first_name }} {{ user.last_name }}
                        {% if user.role == 'admin' %}
                            (admin)
                        {% endif %}
                    </div>
                    <div class="smallertext">
                        {{ user.number }}
                    </div>
                    <div class="smallertext">
                        {{ user.email }}
                    </div>
                </div>
            </a>
            {% endfor %}
            </div>
    </body>
</html>